version: '3.8'
services:
  server:
    build: ./server
    restart: on-failure
    container_name: share-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SERVER_PORT=9090

  gateway:
    build: ./gateway
    container_name: share-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - SERVER_PORT=8080

  db:
    image: postgres:13.7-alpine
    container_name: share-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root